# Generated by Django 6.0.6 on 2026-06-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_topictarget_subject_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_completed',
            new_name='is_mock_completed',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='time_spent_seconds',
            new_name='time_spent_mins',
        ),
        migrations.AddField(
            model_name='subject',
            name='target_minutes',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='topic',
            name='target_minutes',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='topic',
            name='weightage_marks',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_mins', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='tracker.topic')),
            ],
        ),
    ]
