# Generated by Django 6.0.6 on 2026-06-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_is_completed_topic_is_mock_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='time_spent_mins',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_mock_completed',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='target_minutes',
        ),
    ]
