# Generated by Django 6.0.6 on 2026-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_subtopic_time_spent_mins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='time_spent_mins',
            new_name='manual_completion_pct',
        ),
        migrations.AddField(
            model_name='topic',
            name='set_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
