# Generated by Django 6.0.6 on 2026-06-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_time_spent_mins_topic_manual_completion_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logged_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
