# Generated by Django 6.0.6 on 2026-06-29 22:20

from django.db import migrations

def clear_all_production_records(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Exam = apps.get_model('tracker', 'Exam')
    Subject = apps.get_model('tracker', 'Subject')
    Topic = apps.get_model('tracker', 'Topic')
    SubTopic = apps.get_model('tracker', 'SubTopic')

    # Full system purge across the live Neon cloud database tables
    SubTopic.objects.all().delete()
    Topic.objects.all().delete()
    Subject.objects.all().delete()
    Exam.objects.all().delete()
    User.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_topic_logged_seconds'),
    ]

    operations = [
        migrations.RunPython(clear_all_production_records),
    ]